### ISSUE TITLE
Output marks whether blockchain synced at height

### ISSUE THREAD

**Issue by Mitchellpkt** [neptuneresearch/monerod-archive#4]
Analyses that employ miner-reported timestamp (MRT) and node-receipt timestamp (NRT) suffer from artifacts if they include blocks that were downloaded while not fully caught up to the network.

Why Imagine that a MAP archival node goes down for 24 hours, missing about 600 blocks. When it is turned back on, it will very quickly sync up to height. Now consider the first of blocks from the outage: the NRT - MRT is going to be 24 hours, since the node did not receive the blocks until a day later. The NRT's are meaningless, and should be dropped or NaN-ified for future analyses.

This could show up like:
`2018-08-11 15:41:03.566	[P2P3] ALT  H=1636648 MRT=1534002008 NRT=1534002063566 SYNCED=1`

**Comment by neptuneresearch** [comment]
Added in v7: Is Node Synced?, NCH, NTH.
