### ISSUE TITLE
Mark archive output format version

### ISSUE THREAD

**Issue by Mitchellpkt** [neptuneresearch/monerod-archive#5]
In the output files, it would be helpful to indicate output format version.

e.g. original filesystem could be format ver 0, the version with spaces would be format ver 1, and the version with tabs would be format ver 2. When you add at_height indicator, this becomes format ver 3. 

This way, analysis scripts won't crash due to mingling different formats 

(I will just write a universal import wrapper that parses any type, using switch-case on the version number, so the analysis scripts don't even see/interact with the raw output format)

**Comment by neptuneresearch** [comment]
Added in v7.
