### ISSUE TITLE
Anyone has the whole log from its beginning to share?

### ISSUE THREAD

**Issue by janowitz** [neptuneresearch/monerod-archive#6]
I haven't found any public resource about reorgs and maybe would create one, but how to get the whole monerod-archive log? Most probably this has only been implemented at some point, so no data from block 1 would be available. However, does someone have this data which I could use for my own monerod-archive to follow up?

Reference: https://www.reddit.com/r/Monero/comments/st40o0/psa_informational_thread_regarding_the_minexmr/hxpj10j/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by neptuneresearch** [comment]
Hi janowitz,

The issue tracker for monerod-archive is for software issues, like bugs.

We have a discussion forum at `#noncesense-research-lab` on Libera.chat IRC and [Noncesense Research Lab on Monero.social Matrix](https://matrix.to/#/#noncesense-research-lab:monero.social).
